name: chatgpt_windows_flutter_app
description: A chat gpt project for windows created with Flutter.
publish_to: "none"
version: 0.9.9

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.8.7
  system_theme: ^2.3.1
  flutter_acrylic: ^1.1.3
  go_router: ^14.0.1
  provider: ^6.1.1
  url_launcher: ^6.3.0
  window_manager: ^0.3.7
  chat_gpt_sdk: ^3.0.7
  shared_preferences: ^2.2.2
  chat_gpt_flutter: ^1.0.16
  system_tray: ^2.0.3
  hotkey_manager: ^0.2.1
  flutter_markdown: ^0.7.1
  process_run: ^0.14.2
  shell: ^2.0.0
  file: ^6.1.4
  markdown: ^7.1.1
  fluentui_system_icons: ^1.1.246
  rxdart: ^0.28.0
  dio: ^5.4.0
  windows_single_instance: ^1.0.1
  flutter_highlighter: ^0.1.1
  file_picker: ^8.0.3
  background_downloader: ^8.4.0
  cross_file: ^0.3.4+1
  mime_type: ^1.0.0
  pasteboard: ^0.2.0
  easy_image_viewer: ^1.4.1
  path_provider: ^2.1.2
  protocol_handler: ^0.2.0
  package_info_plus: ^8.0.0
  tiktoken: ^1.0.3
  super_drag_and_drop: ^0.8.17
  file_selector: ^1.0.3
  super_clipboard: ^0.8.17
  permission_handler: ^11.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.7

dependency_overrides:
  intl: ^0.19.0
  uuid: ^4.1.0


flutter:
  assets:
    - assets/
  uses-material-design: true

msix_config:
  display_name: Fluent GPT
  publisher_display_name: Realkalash
  msix_version: 0.8.0.0
  logo_path: C:\Users\realk\repos\pet\chatgpt_windows_flutter_app\assets\app_icon.png
  capabilities: internetClient, microphone
  languages: en-us
  protocol_activation: fluentgpt
  app_installer:
    publish_folder_path: msi_flutter_builds
    hours_between_update_checks: 0
    automatic_background_task: false
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false