name: Flutter CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
        with:
          version: stable  # You can specify the desired version here, e.g., "2.5.3"

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS profile
        run: flutter build macos --profile

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-release-build
          path: build/macos/Build/Products/

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # You can specify the desired version here, e.g., "2.5.3"

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-release-build
          path: build/windows/x64/runner/Release
          retention-days: 3
          if-no-files-found: error